package servidorNotificaciones.sop_corba;


/**
* servidorNotificaciones/sop_corba/NotificacionesIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* viernes 19 de junio de 2020 05:04:47 PM COT
*/

public interface NotificacionesIntOperations 
{
  void notificarRegistro (servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTO objNotificacion);
} // interface NotificacionesIntOperations
