package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/ClienteCallbackIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* lunes 22 de junio de 2020 01:26:50 PM COT
*/

public abstract class ClienteCallbackIntPOA extends org.omg.PortableServer.Servant
 implements servidorAlertas.sop_corba.ClienteCallbackIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notificar", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidorAlertas/sop_corba/ClienteCallbackInt/notificar
       {
         String mensaje = in.read_string ();
         this.notificar (mensaje);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorAlertas/sop_corba/ClienteCallbackInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClienteCallbackInt _this() 
  {
    return ClienteCallbackIntHelper.narrow(
    super._this_object());
  }

  public ClienteCallbackInt _this(org.omg.CORBA.ORB orb) 
  {
    return ClienteCallbackIntHelper.narrow(
    super._this_object(orb));
  }


} // class ClienteCallbackIntPOA
