package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/ClienteCallbackIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* lunes 22 de junio de 2020 01:26:50 PM COT
*/

public interface ClienteCallbackIntOperations 
{
  void notificar (String mensaje);
} // interface ClienteCallbackIntOperations
