package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GesAsintomaticosIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* lunes 22 de junio de 2020 01:26:50 PM COT
*/

public abstract class GesAsintomaticosIntPOA extends org.omg.PortableServer.Servant
 implements servidorAlertas.sop_corba.GesAsintomaticosIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarAsintomatico", new java.lang.Integer (0));
    _methods.put ("modificarAsintomatico", new java.lang.Integer (1));
    _methods.put ("enviarIndicadores", new java.lang.Integer (2));
    _methods.put ("consultarRegPermitidos", new java.lang.Integer (3));
    _methods.put ("cambiarRegPermitidos", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servidorAlertas/sop_corba/GesAsintomaticosInt/registrarAsintomatico
       {
         servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTO objAsin = servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTOHelper.read (in);
         servidorAlertas.sop_corba.ClienteCallbackInt objCliente = servidorAlertas.sop_corba.ClienteCallbackIntHelper.read (in);
         boolean $result = false;
         $result = this.registrarAsintomatico (objAsin, objCliente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // servidorAlertas/sop_corba/GesAsintomaticosInt/modificarAsintomatico
       {
         servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTO objAsin = servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTOHelper.read (in);
         String old_tipo_id = in.read_string ();
         int old_id = in.read_long ();
         boolean $result = false;
         $result = this.modificarAsintomatico (objAsin, old_tipo_id, old_id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // servidorAlertas/sop_corba/GesAsintomaticosInt/enviarIndicadores
       {
         servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsIndicadoresDTO objIndi = servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsIndicadoresDTOHelper.read (in);
         boolean $result = false;
         $result = this.enviarIndicadores (objIndi);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // servidorAlertas/sop_corba/GesAsintomaticosInt/consultarRegPermitidos
       {
         int $result = (int)0;
         $result = this.consultarRegPermitidos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // servidorAlertas/sop_corba/GesAsintomaticosInt/cambiarRegPermitidos
       {
         int cantidad = in.read_long ();
         boolean $result = false;
         $result = this.cambiarRegPermitidos (cantidad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servidorAlertas/sop_corba/GesAsintomaticosInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GesAsintomaticosInt _this() 
  {
    return GesAsintomaticosIntHelper.narrow(
    super._this_object());
  }

  public GesAsintomaticosInt _this(org.omg.CORBA.ORB orb) 
  {
    return GesAsintomaticosIntHelper.narrow(
    super._this_object(orb));
  }


} // class GesAsintomaticosIntPOA
