package servidorAlertas.sop_corba;


/**
* servidorAlertas/sop_corba/GesAsintomaticosIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* lunes 22 de junio de 2020 01:26:50 PM COT
*/

public interface GesAsintomaticosIntOperations 
{
  boolean registrarAsintomatico (servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTO objAsin, servidorAlertas.sop_corba.ClienteCallbackInt objCliente);
  boolean modificarAsintomatico (servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsAsintomaticoDTO objAsin, String old_tipo_id, int old_id);
  boolean enviarIndicadores (servidorAlertas.sop_corba.GesAsintomaticosIntPackage.ClsIndicadoresDTO objIndi);
  int consultarRegPermitidos ();
  boolean cambiarRegPermitidos (int cantidad);
} // interface GesAsintomaticosIntOperations
