package servidorAlertas.sop_corba.GesAsintomaticosIntPackage;


/**
* servidorAlertas/sop_corba/GesAsintomaticosIntPackage/ClsIndicadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from salertas.idl
* lunes 22 de junio de 2020 01:26:50 PM COT
*/

public final class ClsIndicadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String tipo_id = null;
  public int id = (int)0;
  public float frecuenciaCardiaca = (float)0;
  public float frecuenciaRespiratoria = (float)0;
  public float temperatura = (float)0;

  public ClsIndicadoresDTO ()
  {
  } // ctor

  public ClsIndicadoresDTO (String _tipo_id, int _id, float _frecuenciaCardiaca, float _frecuenciaRespiratoria, float _temperatura)
  {
    tipo_id = _tipo_id;
    id = _id;
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
  } // ctor

} // class ClsIndicadoresDTO
