package servidorNotificaciones.sop_corba.NotificacionesIntPackage;


/**
* servidorNotificaciones/sop_corba/NotificacionesIntPackage/ClsAsintomaticoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* viernes 19 de junio de 2020 05:04:47 PM COT
*/

public final class ClsAsintomaticoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombres = null;
  public String apellidos = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;

  public ClsAsintomaticoDTO ()
  {
  } // ctor

  public ClsAsintomaticoDTO (String _nombres, String _apellidos, String _tipo_id, int _id, String _direccion)
  {
    nombres = _nombres;
    apellidos = _apellidos;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
  } // ctor

} // class ClsAsintomaticoDTO
