package servidorNotificaciones.sop_corba.NotificacionesIntPackage;

/**
* servidorNotificaciones/sop_corba/NotificacionesIntPackage/ClsNotificacionDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* viernes 19 de junio de 2020 05:04:47 PM COT
*/

public final class ClsNotificacionDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTO value = null;

  public ClsNotificacionDTOHolder ()
  {
  }

  public ClsNotificacionDTOHolder (servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsNotificacionDTOHelper.type ();
  }

}
