package servidorNotificaciones.sop_corba.NotificacionesIntPackage;


/**
* servidorNotificaciones/sop_corba/NotificacionesIntPackage/ClsNotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* viernes 19 de junio de 2020 05:04:47 PM COT
*/

public final class ClsNotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsAsintomaticoDTO asintomatico = null;
  public servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsUltimoIndicadorDTO ultimoIndicador = null;
  public servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsAlertaDTO alerta[] = null;

  public ClsNotificacionDTO ()
  {
  } // ctor

  public ClsNotificacionDTO (servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsAsintomaticoDTO _asintomatico, servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsUltimoIndicadorDTO _ultimoIndicador, servidorNotificaciones.sop_corba.NotificacionesIntPackage.ClsAlertaDTO[] _alerta)
  {
    asintomatico = _asintomatico;
    ultimoIndicador = _ultimoIndicador;
    alerta = _alerta;
  } // ctor

} // class ClsNotificacionDTO
