package servidorNotificaciones.sop_corba.NotificacionesIntPackage;


/**
* servidorNotificaciones/sop_corba/NotificacionesIntPackage/ClsUltimoIndicadorDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from snotificaciones.idl
* viernes 19 de junio de 2020 05:04:47 PM COT
*/

public final class ClsUltimoIndicadorDTO implements org.omg.CORBA.portable.IDLEntity
{
  public float frecuenciaCardiaca = (float)0;
  public float frecuenciaRespiratoria = (float)0;
  public float temperatura = (float)0;

  public ClsUltimoIndicadorDTO ()
  {
  } // ctor

  public ClsUltimoIndicadorDTO (float _frecuenciaCardiaca, float _frecuenciaRespiratoria, float _temperatura)
  {
    frecuenciaCardiaca = _frecuenciaCardiaca;
    frecuenciaRespiratoria = _frecuenciaRespiratoria;
    temperatura = _temperatura;
  } // ctor

} // class ClsUltimoIndicadorDTO
